ALTER TABLE progress_photos ADD COLUMN is_starred INTEGER NOT NULL DEFAULT 0;
ALTER TABLE milestone_photos ADD COLUMN is_starred INTEGER NOT NULL DEFAULT 0;
ALTER TABLE gallery_photos ADD COLUMN is_starred INTEGER NOT NULL DEFAULT 0;
